"""initial domain schema

Revision ID: 8a04017a1a4d
Revises: 
Create Date: 2026-09-26 00:21:06.196983
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8a04017a1a4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_sites_id_organization')
    )
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('current_condition', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'asset_tag', name='uq_assets_site_asset_tag')
    )
    op.create_index('ix_assets_asset_tag', 'assets', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_assets_site_id'), 'assets', ['site_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('upper_management', 'site_management', 'technician', name='user_role'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(role = 'upper_management' AND site_id IS NULL) OR (role <> 'upper_management' AND site_id IS NOT NULL)", name='ck_users_role_site_scope'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id', 'organization_id'], ['sites.id', 'sites.organization_id'], name='fk_users_site_organization', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_users_id_organization')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('inspector_name', sa.String(length=200), nullable=False),
    sa.Column('vibration_reading', sa.Float(), nullable=True),
    sa.Column('visual_condition', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_asset_id'), 'inspections', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inspections_inspection_date'), 'inspections', ['inspection_date'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('performed_by', sa.String(length=200), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_asset_id'), 'maintenance_records', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_date'), 'maintenance_records', ['maintenance_date'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.Enum('high', 'moderate', 'low', name='risk_tier'), nullable=False),
    sa.Column('probability_of_failure', sa.Float(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('is_recurring_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_asset_id'), 'risk_assessments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_inspection_id'), 'risk_assessments', ['inspection_id'], unique=False)
    op.create_table('maintenance_schedule_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.Enum('inspection', 'maintenance', name='schedule_event_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True, comment='Estimated duration in minutes'),
    sa.Column('resources_needed', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='schedule_event_status'), server_default='scheduled', nullable=False),
    sa.Column('source_risk_assessment_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_risk_assessment_id'], ['risk_assessments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_schedule_events_asset_id'), 'maintenance_schedule_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_schedule_events_created_by'), 'maintenance_schedule_events', ['created_by'], unique=False)
    op.create_index(op.f('ix_maintenance_schedule_events_scheduled_date'), 'maintenance_schedule_events', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_maintenance_schedule_events_site_id'), 'maintenance_schedule_events', ['site_id'], unique=False)
    op.create_index(op.f('ix_maintenance_schedule_events_source_risk_assessment_id'), 'maintenance_schedule_events', ['source_risk_assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_schedule_events_source_risk_assessment_id'), table_name='maintenance_schedule_events')
    op.drop_index(op.f('ix_maintenance_schedule_events_site_id'), table_name='maintenance_schedule_events')
    op.drop_index(op.f('ix_maintenance_schedule_events_scheduled_date'), table_name='maintenance_schedule_events')
    op.drop_index(op.f('ix_maintenance_schedule_events_created_by'), table_name='maintenance_schedule_events')
    op.drop_index(op.f('ix_maintenance_schedule_events_asset_id'), table_name='maintenance_schedule_events')
    op.drop_table('maintenance_schedule_events')
    op.drop_index(op.f('ix_risk_assessments_inspection_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_asset_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_maintenance_records_maintenance_date'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_asset_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_inspections_inspection_date'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_asset_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_assets_site_id'), table_name='assets')
    op.drop_index('ix_assets_asset_tag', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_table('organizations')
    # ### end Alembic commands ###
